### ISSUE TITLE
Filter generated modules from docs

### ISSUE THREAD

**Issue by ArthurClemens** [elixir-cldr/cldr_trans#9]
My doc files get polluted with generated `Translations` and `Translations.Fields` over which I don't have any control. Adding `@moduledoc false` would solve this problem.

**Comment by kipcole9** [comment]
Good suggestion, done! I'll publish a new release in the next hour.

**Comment by kipcole9** [comment]
I've published [ex_cldr_trans version 1.1.1](https://hex.pm/packages/ex_cldr_trans/1.1.1) with the following changelog entry:

### Bug Fixes

* Adds `@moduledoc false` to the translations and field generated modules to reduce noise. Thanks to @ArthurClemens for the issue. Closes #9.

### Enhancements

* Improve the clarity of the documentation in the README and the `Cldr.Trans` modules.

**Comment by ArthurClemens** [comment]
The problem is not solved completely: I still get doc files for `MyApp.MyModule.Translations`.

**Comment by kipcole9** [comment]
Oh, I should have mentioned that use of [generate_docs: false](https://hexdocs.pm/ex_cldr/readme.html#backend-module-configuration) on your CLDR backend. Something like:
```elixir
defmodule MyApp.Cldr do
  use Cldr,
    locales: [.....],
    default_locale: "en",
    generate_docs: false

end
```
Can you give that a try and report back?

**Comment by ArthurClemens** [comment]
`generate_docs: false` removes almost all of the Cldr documentation files, but still generates those `X.Translations` files. I also get doc warnings such as `documentation references function "Elixir.MyApp.Cldr.get_locale/0" but it is hidden`.
Having Cldr docs is fine for me, but those empty `X.Translations` doc files don't bring any value.

**Comment by kipcole9** [comment]
Thanks for your patience. It took me a long time to work out that Ecto is generating that module based upon the way the embedded schema is defined and I currently I have no way to `@moduledoc false` on it. 

I can define the embedded schema a different way and add `@moduledoc false` but it's getting late where I am so I will do that in the morning.

**Comment by kipcole9** [comment]
I have published [ex_cldr_trans version 1.1.2](https://hex.pm/packages/ex_cldr_trans/1.1.2) with the following changelog entry. I believe this now means that no docs are generated for the generated modules (Translations and Translations.Fields).

### Bug Fixes

* Manually generates the translations `embedded_schema` (rather than letting Ecto do it) and adds `@moduledoc false` to it to reduce noise. This concludes the work to ensure generated modules don't have docs in them (since they are empty and have no developer value).

**Comment by ArthurClemens** [comment]
Thanks!
